# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'YaoXiu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YaoXiu
  #清除CocoaPods警告
   inhibit_all_warnings! 
  #pod 'AFNetworking'
  #pod 'SDWebImage'
  #字典转模型
  pod 'MJExtension'
  #城市选择器
  #pod 'JFCitySelector'
  #RAC
  pod 'ReactiveObjC','~> 3.0.0'
   #pod 'Masonry'
  pod 'YYModel'
  pod 'GKNavigationBarViewController'
  #提示信息
  pod 'Toast'

  pod 'GPUImage', '~> 0.1.7'
  pod 'JMessage', '~> 3.1.0'

  #pod  'VTMagic'
  #HUD
  #pod 'MBProgressHUD', '~> 0.9.2'
  #键盘管理
  pod 'IQKeyboardManager'
  #pod 'TXLiteAVSDK_Player'  # 腾讯云播放器-独立播放器
  pod 'MJRefresh'
  pod 'GKPageScrollView'
  pod 'JXCategoryView'

end
